version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'main'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'build'
      prefix-development: 'build'
      include: 'scope'
    groups:
      nestjs:
        patterns:
          - '@nestjs/*'
        update-types:
          - 'major'
          - 'minor'
          - 'patch'
      nx:
        patterns:
          - 'nx'
          - '@nx/*'
        update-types:
          - 'major'
          - 'minor'
          - 'patch'
  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'main'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'ci'
      include: 'scope'
