name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4.1.0
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'main'
      - run: pnpm install
      - run: pnpm nx sync:check
      - run: pnpm typecheck
      - run: pnpm build
      - run: pnpm test
      - run: pnpm lint
